dismed_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path(
        "", auth_views.LoginView.as_view(), name="login"
    ),  # Redirige la URL raíz a la vista de inicio de sesión
    path("auth/", include("autenticacion.urls")),
    path("inicio/", include("inicio.urls")),
    path("buscador/", include("buscador.urls")),
    path("departamentos/", include("departamentos.urls")),
    path("unidadesmd/", include("unidadesmd.urls")),
    path("matriz_dispositivos/", include("matriz_dispositivos.urls")),
    path("listado_dispositivos_medicos/", include("listado_dispositivos_medicos.urls")),
    path("matriz_medicamentos/", include("matriz_medicamentos.urls")),
    path("importacion/", include("importacion.urls")),
    path("priorizacion/", include("priorizacion.urls")),
    path("backup_manager/", include("backup_manager.urls")),
    path("user_profiles/", include("user_profiles.urls")),
    path("admin/", admin.site.urls),
]

# Si el proyecto está en modo DEBUG (desarrollo), entonces sirve los archivos media.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

importacion/urls.py
from django.urls import path
from . import views

app_name = "importacion"

urlpatterns = [
    path("", views.upload_matriz, name="upload_matriz"),
    path("registros/", views.registros_importacion, name="registros_importacion"),
]

inicio/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.inicio_view, name="inicio"),
]

dismed_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'head.html' %}
  </head>
  <body>
    {% include 'navbar.html' %}

    <main style="margin-top: 58px">
      <div class="container pt-4">
        {% block content %}

        {% endblock %}
      </div>
    </main>

    {% block scripts %}

    {% endblock %}
    {% include 'footer.html' %}
  </body>
</html>

dismed_project/templates/baselogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'headlogin.html' %}
  </head>
  <body>
    <section class="vh-100 h-custom">
      <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-md-9 col-lg-6 col-xl-5">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp" class="img-fluid" alt="Sample image" />
          </div>
          <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
            {% block content %}

            {% endblock %}
          </div>
        </div>
      </div>
    </section>
    {% include 'footerlogin.html' %}
  </body>
</html>

dismed_project/templates/content.html
{% load static %}

dismed_project/templates/error.html
<!DOCTYPE html>
<html>
<head>
    <title>Error</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }

        h1 {
            font-size: 24px;
            color: #333;
        }

        pre {
            font-size: 14px;
            color: #666;
            background-color: #f8f8f8;
            padding: 10px;
            overflow: auto;
        }
    </style>
</head>
<body>
    <h1>Error</h1>
    <p>{{ error }}</p>
    <h2>Traceback:</h2>
    <pre>{{ traceback }}</pre>
</body>
</html>

dismed_project/templates/footer.html
{% load static %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
<footer></footer>

dismed_project/templates/footerlogin.html
{% load static %}

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<footer>
  <div class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
    <!-- Copyright -->
    <div class="text-white mb-3 mb-md-0">Copyright © 2023. All rights reserved.</div>
    <!-- Copyright -->
  </div>
</footer>

dismed_project/templates/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<title>
  {% block title %}
    DisMed
  {% endblock %}
</title>
<link rel="icon" href="{% static 'favicon.ico' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.css" rel="stylesheet"/>
<link href="{% static 'css/sidebars.css' %}" rel="stylesheet">
<link href="{% static 'css/styles.css' %}" rel="stylesheet">
{% block head %}{% endblock %}
{% block stylesheets %}{% endblock %}

dismed_project/templates/headlogin.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<title>
  {% block title %}
    DisMed - Sistema Colaborativo Matricial
  {% endblock %}
</title>
<link rel="icon" href="{% static 'favicon.ico' %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.css" rel="stylesheet"/>
<link href="{% static 'css/styleslogin.css' %}" rel="stylesheet">

{% block head %}{% endblock %}
{% block stylesheets %}{% endblock %}

dismed_project/templates/navbar.html
{% load static %}

<header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bgblue">
        <div class="position-sticky">
            <div class="list-group list-group-flush mx-3 mt-4">
                <a href="{% url 'inicio' %}" class="list-group-item list-group-item-action py-2 ripple"
                    aria-current="true">
                    <i class="fas fa-tachometer-alt fa-fw me-1"></i><span>Dashboard</span>
                </a>
                <a href="{% url 'buscador' %}" class="list-group-item list-group-item-action py-2 ripple">
                    <i class="fas fa-chart-area fa-fw me-1"></i><span>Buscador</span>
                </a>
                <a href="{% url 'departamentos' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fas fa-lock fa-fw me-1"></i><span>Departamentos</span></a>
                <a href="{% url 'mostrar_unidadesmd' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fas fa-chart-line fa-fw me-1"></i><span>Unidades Médicas</span></a>

                <a class="list-group-item list-group-item-action py-2 ripple" aria-current="true"
                    data-mdb-toggle="collapse" href="#Matrices" aria-expanded="true" aria-controls="Matrices">
                    <i class="fas fa-chart-column fa-fw me-3"></i><span>Matrices</span>
                </a>
                <!-- Collapsed content -->
                <ul id="Matrices" class="collapse list-group list-group-flush">
                    <li class="list-group-item py-1">
                        <a href="{% url 'mostrar_matriz_dispositivos' %}" class="text-reset">
                            <i class="far fa-chart-bar ms-2"></i> Matriz Dispositivos Médicos</a>
                    </li>
                    <li class="list-group-item py-1">
                        <a href="{% url 'mostrar_matriz_medicamentos' %}" class="text-reset">
                            <i class="far fa-chart-bar fa-fw me-1"></i> Matriz Medicamentos</a>
                    </li>
                    <li>
                        <a class="list-group-item list-group-item-action py-2 ripple" aria-current="true"
                            data-mdb-toggle="collapse" href="#Importacion" aria-expanded="true"
                            aria-controls="Importacion">
                            <i class="fas fa-chart-column fa-fw me-3"></i><span>Importación</span>
                        </a>
                        <!-- Collapsed content -->
                        <ul id="Importacion" class="collapse list-group list-group-flush">
                            <li class="list-group-item py-1">
                                <a href="{% url 'importacion:upload_matriz' %}" class="text-reset">
                                    <i class="far fa-chart-bar ms-2"></i> Importar UM</a>
                            </li>
                            <li class="list-group-item py-1">
                                <a href="{% url 'importacion:registros_importacion' %}" class="text-reset">
                                    <i class="far fa-chart-bar fa-fw me-1"></i> Registro Importación UM</a>
                            </li>
                        </ul>
                    </li>
                </ul>

                <a class="list-group-item list-group-item-action py-2 ripple" aria-current="true"
                    data-mdb-toggle="collapse" href="#Listados" aria-expanded="true" aria-controls="Listados">
                    <i class="fas fa-clipboard-list fa-fw me-3"></i><span>Listados</span>
                </a>
                <!-- Collapsed content -->
                <ul id="Listados" class="collapse list-group list-group-flush">
                    <li class="list-group-item py-1">
                        <a href="{% url 'import_excel' %}" class="text-reset">
                            <i class="fas fa-upload ms-2"></i> Importar Listados</a>
                    </li>
                    <li class="list-group-item py-1">
                        <a href="{% url 'listado_dispositivos_medicos' %}" class="text-reset">
                            <i class="fas fa-file-medical fa-fw me-1"></i> Listado Dispositivos Médicos</a>
                    </li>
                    <li class="list-group-item py-1">
                        <a href="#" class="text-reset">
                            <i class="fas fa-book-medical fa-fw me-1"></i> Listado Medicamentos</a>
                    </li>
                </ul>

                <a href="#" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fas fa-building fa-fw me-1"></i><span>Partners</span></a>
                <a href="#" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fas fa-calendar fa-fw me-1"></i><span>Calendar</span></a>
                <a href="#" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fas fa-users fa-fw me-1"></i><span>Users</span></a>
                <a href="#" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fas fa-money-bill fa-fw me-1"></i><span>Sales</span></a>
            </div>
        </div>
    </nav>
    <!-- Sidebar -->

    <!-- Navbar -->
    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bggrey fixed-top">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#sidebarMenu"
                aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <!-- Brand -->
            <a class="navbar-brand" href="{% url 'inicio' %}">DISMED</a>

            <!-- Right links -->
            <ul class="navbar-nav ms-auto d-flex flex-row">
                <!-- Notification dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link me-1 me-lg-0 dropdown-toggle hidden-arrow" href="#" id="navbarDropdownMenuLink"
                        role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-bell"></i>
                        <span class="badge rounded-pill badge-notification bg-danger">1</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="#">Some news</a></li>
                        <li><a class="dropdown-item" href="#">Another news</a></li>
                        <li>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </li>
                    </ul>
                </li>

                <!-- Avatar -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center" href="#"
                        id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                        <img src="https://mdbootstrap.com/img/Photos/Avatars/img (31).jpg" class="rounded-circle"
                            height="22" alt="" loading="lazy" />
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="#">My profile</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
</header>
<!--Main Navigation-->